In [1]:
#Importing Libraries
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from datetime import datetime as dt
from scipy import stats


#Loading Data
df = pd.read_csv('/Users/Kevin/Files/Thinkful/Data Files/ESSdata_Thinkful.csv')

In [2]:
df.head()

,cntry,idno,year,tvtot,ppltrst,pplfair,pplhlp,happy,sclmeet,sclact,gndr,agea,partner
0,CH,5.0,6,3.0,3.0,10.0,5.0,8.0,5.0,4.0,2.0,60.0,1.0
1,CH,25.0,6,6.0,5.0,7.0,5.0,9.0,3.0,2.0,2.0,59.0,1.0
2,CH,26.0,6,1.0,8.0,8.0,8.0,7.0,6.0,3.0,1.0,24.0,2.0
3,CH,28.0,6,4.0,6.0,6.0,7.0,10.0,6.0,2.0,2.0,64.0,1.0
4,CH,29.0,6,5.0,6.0,7.0,5.0,8.0,7.0,2.0,2.0,55.0,1.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8594 entries, 0 to 8593
Data columns (total 13 columns):
cntry      8594 non-null object
idno       8594 non-null float64
year       8594 non-null int64
tvtot      8586 non-null float64
ppltrst    8580 non-null float64
pplfair    8555 non-null float64
pplhlp     8569 non-null float64
happy      8563 non-null float64
sclmeet    8579 non-null float64
sclact     8500 non-null float64
gndr       8584 non-null float64
agea       8355 non-null float64
partner    8577 non-null float64
dtypes: float64(11), int64(1), object(1)
memory usage: 872.9+ KB

# Answers

- cntry 
    - object
    - Country
    - Categorical 
- idno
    - float64
    - ID Number
    - Categorical
- year
    - int64
    - Year
    - Categorical
- tvtot
    - float64
    - TV Watching - total time on average weekday - 0 (do not watch tv) & 7 (more than 3 hours)
    - Continuous - Interval Variable
- ppltrst
    - float64
    - Trust level - 0 (not trustworthy) & 10 (being trust worthy)
    - Continuous - Ordinal Variable
- pplfair
    - float64
    - Likelihood of people taking advantage of you - 0 (Everyone takes advantage of you) & 10 (Everyone treats you fairly)
    - Continuous - Ordinal Variable
- pplhlp
    - float64
    - Likelihood of people being helpful - 0 (people only look out for themselves) & 10 (people are helpful)
    - Continuous - Ordinal Variable
- happy
    - float64
    - How happy are you - 0 (unhappy) & 10 (very happy)
    - Continuous - Ordinal Variable
- sclmeet
    - float64
    - How often you meet with friends - 1 (never) & 7 (everyday)
    - Continuous - Ordinal Variable
- sclact
    - float64
    - Compared to other people of your age, how often would you say you take part in social activities ? - 1 (much less than most) & 5 (Much more than most)
    - Continuous - Ordinal Variable
- gndr
    - float64
    - Gender - 1 (male) & 2 (female)
    - Categorical
- agea
    - float64
    - Age 
    - Continuous - Ratio Variable
- partner 
    - float64
    - Lives with SO at household - 1 (Yes) & 2 (No)
    - Categorical